### ISSUE TITLE
user_id for ideogram

### ISSUE THREAD

**Issue by OlegRuban-ai** [brainboost/chatgpt-telegram-bot#17]
Good evening! Where can I find out user_id for ideogram.ai? Can't get it anywhere

**Comment by brainboost** [comment]
Heyo, user_is was reversed from the site, you need to login, open devtools, make a new prompt and look for post with json body like that 
![image](https://github.com/brainboost/chatgpt-telegram-bot/assets/1145520/7e73dc8f-aa3c-4afb-ae21-7bd9285a9bfe). Hope it will help you

**Comment by brainboost** [comment]
It works, the only drawback is needing manually update the token from time to time. Actually, I don't know if ideogram uses cloudflare's protection at all
