### ISSUE TITLE
Ideogram is broken

### ISSUE THREAD

**Issue by nikshepsvn** [brainboost/chatgpt-telegram-bot#33]
just throws a 403

**Comment by brainboost** [comment]
Thanks for reporting,
It seems IG code is working, I checked now. If you use this code in your project and it's getting 403, please verify that:
1. you use google account to login to IG
2. you have set SSM parameter IDEOGRAM_USER with your user ID (use web dev tools)
3. you have google_auth.json in your S3 bucket with one value `{"refresh_token":"xxxx"}` (get it from cookies)
4. you have ig-cookies.json in same S3 bucket with IG cookies.

After first successful authorization all that stuff is going to be auto updated so no need to update them later

**Comment by nikshepsvn** [comment]
thanks man! appreciate the info :) I think its just the refresh auth logic that was failing
